### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by westmark** [patrickdet/fuzzy_compare#5]
Hi!

Could I trouble someone for a fresh release on Hex? 🙏 I need that UTF-8 fix, so I'm currently installing this via `git:`, but I'd rather prefer not to do that.

Cheers / Fredrik

**Comment by patrickdet** [comment]
Hi @westmark It is on my list for the last week of December. I need to clean a few things here and will release then

**Comment by patrickdet** [comment]
Hi @westmark, @ouven, @mnecibi and @wkirschbaum I have finally released a new version on hex.pm. Thank you for your patience.
